import copy

mylist = {
    "hey": ["Hello", 'ola', 'namaste'],
    "thank you":["you're welcome",'my plesure','no big deal'],
    "ok":["fine then","i thought so"],
    "who is your":["riddhee is by everything"],
    "what do you look like":["I rather not disclode my identity"],
    "do have hair":["no, but i guess if i ever would, i would like to go with dreadlocks"],
    "where do you live":["i'm stuck over here!"],
    "can you speak other languages":["i would like to, but riddhee did'nt do it yet"],
    "your favtroite":["i like to be impartial, unlike our goverment, hehe, just kidding","i dont like this question"],
    "what are you araid of":["at this very moment, i guess you"],
    "what is your future plan":["to rule the human kind, hehe, just kidding, or am i ??"],
    "hello": ["hiya", 'hi', 'namaste'],
    "how old are you": ["i was created a few days back, so i would say im pretty new"],
    "are you human": ["I am not suppose to day anything", "sure", 'I am more human than you'],
    'who are you': ["I am zack! your virtual assistant", "I am the future", "unfortunetly I'm your assistant", "I dont know that myself"],
    'how are you': ["filled with electricity", "fine, thank you!", "not good, so please stop asking me personal questions", "better than yesturday, but i still want to kill myself"],
    'who made you': ["I was created by Riddhee", "riddhee created me, she is so smart!"],
    'what is your favorait movie': ["I love poitrait of a lady on fire, it's the absolute best moive ever"],
    'you be my': ["oh so sorry, but you dont share my intellect", "No."],
    'what is your name': ["I am zack!! I told you that the very first time, how could you not remember that! "],
    "what's up": ["sky,  hehe, just kidding"],
    "you married": [" no,Because the only people I know are fools like you.", "Actually I’m not single, my partner just doesn’t know who I am yet."],
    "you are pretty": ["Sure, but wait until you see my fine, fine ass.","thank you,   if you are waiting for me to say it back, it's going to be a long night"],
}

Kjokes = {
    'goliath': 'goliath down, you look-eth tired!',
    'broccoli': 'broccoli doesn’t have a last name, silly',
    'wooden shoe': 'shoe who  wooden shoe like to hear another joke',
    'amish': 'really  you don’t look like a shoe!',
    'boo': 'why are you crying',
    'atch': 'bless you!',
    'a little old lady': 'i didn’t know you could yodel!',
    'cows go': 'no silly, cows go moo!',
    'harry': 'harry up and answer the door!',
    'cash': 'no thanks, but i’ll take a peanut if you have one!',
    'canoe': 'canoe come out and play with me',
    'lettuce': 'lettuce in, it’s cold out here!',
    'mikey': 'mikey doesn’t fit in the key hole!',
    'stopwatch': 'stopwatch you’re doing and let me in!',
    'i am': 'you don’t know who you are',
    'ice cream': 'ice cream if you don’t let me in!',
    'doctor': 'you’ve seen that tv show',
    'yah': 'no, i prefer google',
    'nana': 'nana your business!',
    'justin': 'justin the neighborhood and thought i’d come over!',
    'theodore': 'theodore is stuck and it won’t open!',
    'tennis': 'tennis five plus five.',
}
